In [7]:
# question 1
import numpy as np
new_array=np.array([[1,2,3],[4,5,6]])
new_array=new_array.tolist()
print(new_array)

[[1, 2, 3], [4, 5, 6]]


In [10]:
# question 2
import numpy as np
new_array=np.array([[1,2,3],[4,5,6]])
valeur=np.trace(np.new_array)
print(valeur)

6


In [22]:
# question 3
import numpy as np
new_array=np.array([[1,2,3],[4,5,6]])
x = 2
print(new_array[new_array>x])

[3 4 5 6]


In [18]:
# question 4
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[4,5,9],[6,5,8]])
c=a+b
print(c)

[[ 5  7 12]
 [10 10 14]]


In [19]:
# question 5
import numpy as np
new_array=np.array([[1,2,3],[4,5,6]])
moyen=np.mean(new_array)
print(moyen)

3.5
